### YamlMime:FAQ
metadata:
  title: 'Solución de problemas de roles de Azure AD asignados a grupos: Azure Active Directory'
  description: Estas son algunas preguntas y sugerencias para solucionar problemas comunes para la asignación de roles a grupos en Azure Active Directory.
  services: active-directory
  author: rolyon
  manager: daveba
  ms.service: active-directory
  ms.workload: identity
  ms.subservice: roles
  ms.topic: article
  ms.date: 11/05/2020
  ms.author: rolyon
  ms.reviewer: vincesm
  ms.custom: it-pro
  ms.collection: M365-identity-device-management
  ms.openlocfilehash: c09bcdde3713f3ab93814cc67b23ded5cc49c17d
  ms.sourcegitcommit: 106f5c9fa5c6d3498dd1cfe63181a7ed4125ae6d
  ms.translationtype: HT
  ms.contentlocale: es-ES
  ms.lasthandoff: 11/02/2021
  ms.locfileid: "131057141"
title: Solución de problemas de roles de Azure AD asignados a grupos
summary: Estas son algunas preguntas y sugerencias para solucionar problemas comunes para la asignación de roles de Azure Active Directory (Azure AD) a grupos de Azure AD.
sections:
- name: Omitido
  questions:
  - question: >
      Soy administrador de grupos, pero no veo el modificador "Los roles de Azure AD se pueden asignar a un grupo".
    answer: >
      Solo los administradores de roles con privilegios o los administradores globales pueden crear un grupo apto para la asignación de roles. Solo los usuarios de esos roles ven este control.
  - question: >
      ¿quién puede modificar la pertenencia de grupos asignados a roles de Azure AD?
    answer: >
      de forma predeterminada, solo los administradores de roles con privilegios y los administradores globales administran la pertenencia de un grupo al que se pueden asignar roles, pero puede delegar la administración de grupos a los que se pueden asignar roles agregando propietarios del grupo.
  - question: >
      Soy administrador del departamento de soporte técnico en mi organización, pero no puedo actualizar la contraseña de un usuario que sea lector del directorio. ¿Por qué ocurre eso?
    answer: >
      El usuario podría haber conseguido un lector del directorio por medio de un grupo al que se pueden asignar roles. Todos los miembros y propietarios de un grupo al que se pueden asignar roles están protegidos. Solo los usuarios de los roles Administrador de autenticación con privilegios o Administrador global pueden restablecer las credenciales de un usuario protegido.
  - question: >
      no puedo actualizar la contraseña de un usuario. No se les ha asignado ningún rol con privilegios superior. ¿Por qué está sucediendo?
    answer: "el usuario podría ser propietario de un grupo al que se pueden asignar roles. Protegemos a los propietarios de grupos a los que se pueden asignar roles para evitar la elevación de privilegios. Un ejemplo podría ser si se asigna un grupo Contoso_Security_Admins al rol Administrador de seguridad, donde Bob es el propietario del grupo y Alice es el administrador de contraseñas de la organización. Si no estuviera presente esta protección, Alice podría restablecer las credenciales de Bob y asumir su identidad. A continuación, Alice podría agregarse a sí misma o a cualquier persona al grupo Contoso_Security_Admins para convertirse en Administrador de seguridad de la organización. Para averiguar si un usuario es el propietario de un grupo, obtenga la lista de objetos pertenecientes a dicho usuario y compruebe si alguno de los grupos tiene isAssignableToRole establecido en true. En caso afirmativo, ese usuario está protegido y el comportamiento es por diseño. Consulte estos documentos para obtener objetos en propiedad:\n\n- [Get-AzureADUserOwnedObject](/powershell/module/azuread/get-azureaduserownedobject)  \n- [Enumeración de ownedObjects](/graph/api/user-list-ownedobjects?tabs=http)\n"
  - question: "¿puedo crear una revisión de acceso en grupos que puedan asignarse a roles de Azure AD (en concreto, grupos con la propiedad isAssignableToRole establecida en true)?  \n"
    answer: >
      Sí, puede hacerlo. Los administradores globales y los administradores que tengan un rol con privilegios pueden crear revisiones de acceso en grupos asignables de rol.
  - question: >
      ¿puedo crear un paquete de acceso e incluir en él grupos que puedan asignarse a roles de Azure AD?
    answer: "Sí, puede hacerlo. El administrador global y el administrador de usuarios tienen la capacidad de incluir cualquier grupo en un paquete de acceso. En el caso del administrador global, no se produce ningún cambio. Sin embargo, hay un ligero cambio en los permisos del rol Administrador de usuarios. Para incluir un grupo asignable del rol en un paquete de acceso, debe ser administrador de usuarios y también propietario del grupo asignable del rol. Esta es la tabla completa donde se muestra quién puede crear un paquete de acceso en la administración de licencias Enterprise:\n\nRol de directorio de Azure AD | Rol de administración de derechos | Puede agregar grupos de seguridad\\* | Puede agregar grupos de Microsoft 365\\* | Puede agregar aplicaciones | Puede agregar sitios de SharePoint Online\n----------------------- | --------------------------- | ----------------------- | ------------------------- | ----------- |  -----------------------------\nAdministrador global | N/D | ✔️ | ✔️ | ✔️  | ✔️\nAdministrador de usuarios  | N/D  | ✔️  | ✔️  | ✔️\nAdministrador de Intune | Propietario del catálogo | ✔️  | ✔️  | &nbsp;  | &nbsp;\nAdministrador de Exchange  | Propietario del catálogo  | &nbsp; | ✔️  | &nbsp;  | &nbsp;\nAdministrador del servicio Teams | Propietario del catálogo  | &nbsp; | ✔️  | &nbsp;  | &nbsp;\nAdministrador de SharePoint | Propietario del catálogo | &nbsp; | ✔️  | &nbsp;  | ✔️ \nAdministrador de aplicaciones | Propietario del catálogo  | &nbsp;  | &nbsp; | ✔️  | &nbsp;\nAdministrador de aplicaciones en la nube | Propietario del catálogo  | &nbsp;  | &nbsp; | ✔️  | &nbsp;\nUsuario | Propietario del catálogo | Solo si es propietario del grupo | Solo si es propietario del grupo | Solo si es propietario de la aplicación  | &nbsp;\n\n\\*Al grupo no se le pueden asignar roles; es decir, isAssignableToRole = false. Si a un grupo se le pueden asignar roles, la persona que crea el paquete de acceso también debe ser propietaria del grupo asignable del rol.\n"
  - question: >
      no encuentro la opción "Quitar asignación" en "Roles asignados". ¿Cómo elimino la asignación de roles a un usuario?
    answer: >
      esta respuesta solo es aplicable a las organizaciones Azure AD Premium P1.


      1. Inicie sesión en [Azure Portal](https://portal.azure.com) o el [centro de administración de Azure AD](https://aad.portal.azure.com) y abra **Azure Active Directory**.

      1. Seleccione usuarios y abra un perfil de usuario.

      1. Seleccione **Roles asignados**.

      1. Seleccione el icono de engranaje. Se abre un panel que puede proporcionar esta información. Hay un botón "Quitar" junto a las asignaciones directas. Para quitar la asignación indirecta de roles, quite el usuario del grupo al que se le ha asignado el rol.
  - question: >
      ¿cómo veo todos los grupos a los que se pueden asignar roles?
    answer: >
      Siga estos pasos:


      1. Inicie sesión en [Azure Portal](https://portal.azure.com) o el [centro de administración de Azure AD](https://aad.portal.azure.com) y abra **Azure Active Directory**.

      1. Seleccione **Grupos** > **Todos los grupos**.

      1. Seleccione **Agregar filtros**.

      1. Filtre para **Rol asignable**.
  - question: >
      ¿cómo sabe qué rol se asigna directa o indirectamente a una entidad de seguridad?
    answer: >
      Siga estos pasos:


      1. Inicie sesión en [Azure Portal](https://portal.azure.com) o el [centro de administración de Azure AD](https://aad.portal.azure.com) y abra **Azure Active Directory**.

      1. Seleccione usuarios y abra un perfil de usuario.

      1. Seleccione **Roles asignados** y, a continuación:

          - En las organizaciones con licencia Azure AD Premium P1: seleccione el icono de engranaje. Se abre un panel que puede proporcionar esta información.
          - En las organizaciones con licencia Azure AD Premium P2: encontrará información sobre licencias directas y heredadas en la columna **Pertenencia**.
  - question: "¿Por qué exigimos la creación de un nuevo grupo para asignarlo al rol?  \n"
    answer: >
      si asigna un grupo existente a un rol, el propietario del grupo existente podría agregar otros miembros a este grupo sin saber los nuevos miembros que tendrán el rol. Dado que los grupos a los que se pueden asignar roles son eficaces, ponemos muchas restricciones para protegerlos. No quiere cambios en el grupo inesperados para la persona que administra el grupo.
additionalContent: "\n## <a name=\"next-steps\"></a>Pasos siguientes\n\n- [Uso de grupos de Azure AD para administrar asignaciones de roles](groups-concept.md)\n- [Creación de un grupo al que se pueden asignar roles](groups-create-eligible.md)\n"
